trigger: 
- main
pr: none
jobs:
- job: DockerBuild

  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - task: Docker@2
    inputs:
      containerRegistry: 'Docker Hub'
      repository: 'nikeshi/databaseAutomationTesting'
      command: 'buildAndPush'
      Dockerfile: 'database-automation-testing/app/src/data-backed-service/DOCKERFILE'
      buildContext: 'database-automation-testing/'
      tags: |
        latest
