trigger: 
- main
pr: none
jobs:
- job: DockerBuild

  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - task: Docker@2
    inputs:
      containerRegistry: 'Docker Hub'
      repository: 'nikeshi/databaseAutomationTesting'
      command: 'buildAndPush'
      Dockerfile: 'app/src/data-backed-service/Dockerfile'
      buildContext: 'app/src/data-backed-service/'
      tags: |
        latest
  - script: |
      docker run -d -p 8088:8080 nikeshi/databaseAutomationTesting:v1
      sleep 120
      curl http://localhost:8080/employees
