trigger: 
- main
pr: none
jobs:
- job: DockerBuild

  pool:
    vmImage: 'ubuntu-latest'
  steps:
#  - task: Docker@2
#    inputs:
#      containerRegistry: 'Docker Hub'
#      repository: 'nikeshi/databaseAutomationTesting'
#      command: 'buildAndPush'
#      Dockerfile: 'app/src/data-backed-service/Dockerfile'
#      buildContext: 'app/src/data-backed-service/'
#      tags: |
#        latest
  - script: |
      docker pull liquibase/liquibase
      liquibase --username=$(USER) --password=$(PASSWORD)  --url jdbc:sqlserver://35.244.39.57:3306/DBdev; --labels=v1 validate
    workingDirectory: db
    displayName: 'Verify Changes'
#      docker run --rm -v db:/liquibase/changelog liquibase/liquibase --changelog-file=master.mysql.xml --url=jdbc:postgresql://35.244.39.57:3306/DBdev --username=nikeshi --password=Wso2@321 --defaultsFile=db/liquibase.properties update

