trigger: 
- main
pr: none
resources:
  containers: 
  - container: Liquibase
    image: liquibase/liquibase:4.11.0 
    imagePullPolicy: IfNotPresent
    name: liquibase
stages:
- stage: Build
  jobs:
  - job: DockerBuild
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - checkout: self
    - task: Docker@2
      inputs:
        containerRegistry: 'Docker Hub'
        repository: 'nikeshi/databaseAutomationTesting'
        command: 'buildAndPush'
        Dockerfile: 'app/src/data-backed-service/Dockerfile'
        buildContext: 'app/src/data-backed-service/'
        tags: |
          v1 
    # - script: |
    #     docker run -d -p 8083:8083 nikeshi/databaseAutomationTesting:v1
  - job: DockerBuildLiquibase
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - checkout: self
    - task: Docker@2
      inputs:
        containerRegistry: 'Docker Hub'
        repository: 'nikeshi/liquibase'
        command: 'buildAndPush'
        Dockerfile: 'liquibase/Dockerfile'
        buildContext: 'liquibase/'
        tags: |
          v1 
- stage: Test
  jobs:
  - job: TestLiquibase
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - checkout: self
    - script: |
        liquibase --defaultsFile=changelog/liquibase.properties --changelogfile=changelog/db/master.mysql.xml  --url jdbc:mysql://35.244.39.57:3306/DBdev --driver=com.mysql.cj.jdbc.Driver --classpath=changelog/lib/mysql-connector-java-8.0.29.jar --logLevel=info validate
    displayName: 'Verify Changes'
- stage: Deploy
  jobs:
  - job: DeployDB
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - checkout: self
    - script: |
        liquibase --defaultsFile=changelog/liquibase.properties --changelogfile=changelog/db/master.mysql.xml  --url jdbc:mysql://35.244.39.57:3306/DBdev --driver=com.mysql.cj.jdbc.Driver --classpath=changelog/lib/mysql-connector-java-8.0.29.jar --logLevel=info updateSQl
    displayName: 'Deploy'


  # - script: |
  #     ls -R
  #   displayName: 'File directory'
  # - script: |
  #     docker pull liquibase/liquibase:4.11.0
  #     docker run --rm -v Liquibase:/liquibase/changelog liquibase/liquibase:4.11.0 --defaultsFile=changelog/liquibase.properties --changelogfile=changelog/db/master.mysql.xml  --url jdbc:mysql://35.244.39.57:3306/DBdev --driver=com.mysql.cj.jdbc.Driver --classpath=changelog/lib/mysql-connector-java-8.0.29.jar --logLevel=info updateSQL
  #   displayName: 'Verify Changes'
  # - script: |
  #     docker run --rm -v Liquibase:/liquibase/changelog liquibase/liquibase:4.11.0 --defaultsFile=changelog/liquibase.properties --changelogfile=changelog/db/master.mysql.xml  --url jdbc:mysql://35.244.39.57:3306/DBdev --driver=com.mysql.cj.jdbc.Driver --classpath=changelog/lib/mysql-connector-java-8.0.29.jar --logLevel=info update
  #   displayName: 'Deploy Changes'

