trigger: 
- main
pr: none
parameters:
  - name: version
    displayName: Enter changelog file version
    type: string
    default: v.1.0
variables:
- group: db-dev
resources:
  containers: 
  - container: Liquibase
    image: nikeshi/liquibase:v1 
stages:
- stage: updatingDatabase
  pool:
    vmImage: 'ubuntu-latest'
  jobs:
  - job: TestLiquibase 
    container: Liquibase
    steps:
    - checkout: self
    - script: |
        liquibase --defaultsFile=Liquibase/liquibase.properties --logLevel=info validate
#        liquibase --defaultsFile=Liquibase/liquibase.properties --logLevel=info
        liquibase --defaultsFile=Liquibase/liquibase.properties --logLevel=info status --verbose
    displayName: 'Verify Changes'
  - job: Verify  
    container: Liquibase
    steps:
    - checkout: self
    - script: |
        liquibase --defaultsFile=Liquibase/liquibase.properties  updateSQl
    displayName: 'Verfy Deployment'

- stage: Deploy
  dependsOn: updatingDatabase
  pool:
    vmImage: 'ubuntu-latest'
  jobs:
  - job: DeployDB
    container: Liquibase    
    steps:
    - checkout: self
    - script: |
        liquibase --defaultsFile=Liquibase/liquibase.properties --logLevel=info update
#        liquibase --defaultsFile=Liquibase/liquibase.properties --changelogfile=Liquibase/db/changelog/changelog-${{parameters.version}}.mysql.sql --url jdbc:mysql://0.tcp.ap.ngrok.io:16339/DBdev --username=$(DEVUSERNAME) --password=$(DEVPASSWORD) --driver=com.mysql.cj.jdbc.Driver --classpath=Liquibase/lib/mysql-connector-java-8.0.29.jar --logLevel=info --labels=v.1.0 update
    displayName: 'Finalize'
