trigger: 
- main
pr: none
jobs:
- job: DockerBuild

  pool:
    vmImage: 'ubuntu-latest'
  steps:
#  - task: Docker@2
#    inputs:
#      containerRegistry: 'Docker Hub'
#      repository: 'nikeshi/databaseAutomationTesting'
#      command: 'buildAndPush'
#      Dockerfile: 'app/src/data-backed-service/Dockerfile'
#      buildContext: 'app/src/data-backed-service/'
#      tags: |
#        latest
  - script: |
      docker pull liquibase/liquibase
      docker run --rm -v db:/liquibase/changelog liquibase/liquibase --changelog-file=master.mysql.xml --defaultsFile=db/liquibase.properties update

