trigger: 
  paths:
    include:
    - Liquibase/
    - .azure/build-pipeline.yaml
pr: none
parameters:
  - name: version
    displayName: Enter changelog file version
    type: string
    default: v.1.0
variables:
- group: db-dev
resources:
  containers: 
  - container: Liquibase
    image: nikeshi/liquibase:v1
stages:
- stage: updatingDatabase
  pool:
    vmImage: 'ubuntu-latest'
  jobs:
  - job: TestLiquibase 
    container: Liquibase
    steps:
    - checkout: self
    - script: |
        liquibase --defaultsFile=Liquibase/liquibase.properties --logLevel=info validate
        liquibase --defaultsFile=Liquibase/liquibase.properties --logLevel=info tag nikeshi_$(Build.SourceVersion)
        liquibase --defaultsFile=Liquibase/liquibase.properties --logLevel=info status --verbose
        liquibase --defaultsFile=Liquibase/liquibase.properties  updateSQl
    displayName: 'Verify Changes'
- stage: Deploy
  dependsOn: updatingDatabase
  pool:
    vmImage: 'ubuntu-latest'
  jobs:
  - job: DeployDB
    container: Liquibase    
    steps:
    - checkout: self
    - script: |
        liquibase --defaultsFile=Liquibase/liquibase.properties --logLevel=info update
    displayName: 'Finalize'
