trigger: 
- main
pr: none
resources:
  containers: 
  - container: Liquibase
    image: nikeshi/liquibase:v1 
stages:
- stage: Test
  # dependsOn: []
  pool:
    vmImage: 'ubuntu-latest'
  jobs:
  - job: TestLiquibase
    container: Liquibase    
    steps:
    - checkout: self
    - script: |
        liquibase --defaultsFile=Liquibase/liquibase.properties --changelogfile=Liquibase/db/master.mysql.xml  --url jdbc:mysql://0.tcp.ap.ngrok.io:18386/DBdev --driver=com.mysql.cj.jdbc.Driver --classpath=Liquibase/lib/mysql-connector-java-8.0.29.jar --logLevel=info validate
        liquibase --defaultsFile=Liquibase/liquibase.properties --changelogfile=Liquibase/db/master.mysql.xml  --url jdbc:mysql://0.tcp.ap.ngrok.io:18386/DBdev --driver=com.mysql.cj.jdbc.Driver --classpath=Liquibase/lib/mysql-connector-java-8.0.29.jar --logLevel=info status --verbose
    displayName: 'Verify Changes'
- stage: Deploy
  dependsOn: Test
  pool:
    vmImage: 'ubuntu-latest'
  jobs:
  - job: DeployDB
    container: Liquibase    
    steps:
    - checkout: self
    - script: |
        liquibase --defaultsFile=Liquibase/liquibase.properties --changelogfile=Liquibase/db/master.mysql.xml --url jdbc:mysql://0.tcp.ap.ngrok.io:18386/DBdev --driver=com.mysql.cj.jdbc.Driver --classpath=Liquibase/lib/mysql-connector-java-8.0.29.jar --logLevel=info updateSQl
        liquibase --defaultsFile=Liquibase/liquibase.properties --changelogfile=Liquibase/db/changelog/changelog1.mysql.sql --url jdbc:mysql://0.tcp.ap.ngrok.io:18386/DBdev --driver=com.mysql.cj.jdbc.Driver --classpath=Liquibase/lib/mysql-connector-java-8.0.29.jar --logLevel=info update
    displayName: 'Finalize'
