trigger: 
- main
pr: none
jobs:
- deployment: Deploy
  displayName: Deploy
  pool:
    vmImage: 'ubuntu-latest'
  environment: Kubernetes
  strategy:
    runOnce:
      deploy:
        steps:
        - checkout: self
        - script: |
            ls
            pwd
            cat deployment.yaml
        - task: KubernetesManifest@0
          inputs:
            action: 'deploy'
            kubernetesServiceConnection: 'Kubernetes'
            namespace: 'my-kubernetes'
            manifests: 'deployment.yaml'