trigger: 
  branches:
    include:
    - main
  paths:
    include:
    - Liquibase/
    - .azure/docker-run.yml
pr: none
resources:
  containers: 
  - container: Liquibase
    image: nikeshi/liquibase:v1
parameters:
- name: environment
  type: string
  default: db-dev

variables:
- group: ${{parameters.environment}}
- name: info
  value: "--url=jdbc:mysql://0.tcp.ap.ngrok.io:12568/DBdev --changelog-file=Liquibase/db/master.mysql.yaml --driver= com.mysql.cj.jdbc.Driver --classpath=Liquibase/lib/mysql-connector-java-8.0.29.jar --username=$(devusername) --password=$(devpassword) --logLevel=info"
stages:
- stage: UpdatingDatabase
  pool:
    vmImage: 'ubuntu-latest'
  jobs:
  - job: Run
    steps:
    - task: Docker@2
      displayName: Login 
      inputs:
        command: login
        containerRegistry: 'Docker Hub'
    - task: PowerShell@2
      inputs:
        displayName: Run 
        targetType: inline
        script: |
          docker run nikeshi/liquibase:v1 $(info) update