trigger: 
  branches:
    include:
    - main
  paths:
    include:
    - Liquibase/
    - .azure/docker-run.yml
pr: none
resources:
  containers: 
  - container: Liquibase
    image: nikeshi/liquibase:v1
parameters:
- name: environment
  type: string
  default: db-dev

variables:
- group: ${{parameters.environment}}
- name: info
  value: '--url=jdbc:mysql://0.tcp.ap.ngrok.io:18304/DBdev --changelog-file=db/master.mysql.yaml --classpath=${CLASSPATH} --driver=${DRIVER} --username=$(devusername) --password=$(devpassword) --logLevel=info'
stages:
- stage: UpdatingDatabase
  pool:
    vmImage: 'ubuntu-latest'
  jobs:
  - job: Run
    steps:
    - script: |
        docker run nikeshi/liquibase:v1 $(info) update-sql