trigger: 
  branches:
    include:
    - main
  paths:
    include:
    - Liquibase/
    - .azure/generate.yml
pr: none
resources:
  containers: 
  - container: Liquibase
    image: nikeshi/liquibase:v1
parameters:
- name: environment
  type: string
  default: db-dev

variables:
- group: ${{parameters.environment}}
- name: info
  value: '--url=jdbc:mysql://0.tcp.in.ngrok.io:12008/DB --changelogFile=nik/changelog.yml --driver=${DRIVER} --classpath=${CLASSPATH} --username=$(devusername) --password=$(devpassword) --logLevel=info'
stages:
- stage: UpdatingDatabase
  pool:
    vmImage: 'ubuntu-latest'
  jobs:
  - job: VerifyLiquibase 
    # dependsOn: CheckChanges
    # condition: eq(dependencies.CheckChanges.outputs['check_changes.SOURCE_CODE_CHANGED'], 'true')
    container: Liquibase
    steps:
    - checkout: self
    - script: |
        liquibase $(info) validate
    - script: |       
        liquibase $(info) tag version_$(Build.SourceVersion)
        liquibase $(info) status --verbose
        liquibase $(info) updateSQl
    displayName: 'Verify Changes'
  - job: DeployDB
    dependsOn: VerifyLiquibase
    container: Liquibase    
    steps:
    - checkout: self
    - script: |
        liquibase $(info) update
    displayName: 'Finalize'
