resources:
  repositories:
    - repository: BASE_REPOSITORY
      type: github
      name: nikeshi99/git-log
      ref: refs/heads/main
      endpoint: nikeshi99
trigger: 
  branches:
    include:
    - main
  paths:
    include:
    - .azure/git-diff.yaml
    - logs/
pr: none

stages:
- stage: UpdatingDatabase
  pool:
    vmImage: 'ubuntu-latest'
  jobs:
  - job: CheckChanges
    displayName: 'Check changes'
    steps:
    - checkout: self
      persistCredentials: true
    - script: |
        push_git_changers () {
          git config --global user.email "nikeshikumarasinghe@gmail.com"
          git config --global user.name "Nikeshi Kumarasinghe"
          git diff
          git commit -am "Update succeeded commithash in $(Build.SourceVersion)"
          git remote -v
          git branch -al
          if git push origin HEAD:main ; then
            echo "Changes pushed successfully"
          else
            git fetch origin
            git merge --no-edit --strategy recursive --strategy-option theirs origin/main
            git push origin HEAD:main
          fi
        }
        if [ -s version/commithash.txt ]; then
          previous=$(cat version/commithash.txt)
          PATH_FILTER="logs"
          lenth=${#PATH_FILTER}
          CHANGED_FILES=$(git diff $previous...$(Build.SourceVersion) --name-only | xargs -L1 dirname | uniq)
          MATCH_COUNT=0
          CHANGED_FOLDERS=""
          for FILE in $CHANGED_FILES
          do
            if [[ $FILE == *$PATH_FILTER* ]]; then
              CHANGED_FOLDERS="$(echo "${FILE:$(($lenth+1))})" $CHANGED_FOLDERS"
              echo "MATCH:  ${FILE} changed"
              MATCH_COUNT=$(($MATCH_COUNT+1))
            else
              echo "IGNORE: ${FILE} changed"
            fi
          done
          for i in $CHANGED_FOLDERS
          do
            p=`echo -e $p'\n'$i`
          done
          echo $p
          s=$CHANGED_FOLDERS | tr ' ' ,
          IFS=' ' read -r -a array <<< "$CHANGED_FOLDERS"
          echo "*****ARRAY****"
          echo "${array[*]}"
          echo "***************"
          echo "$MATCH_COUNT match(es) for filter '$PATH_FILTER' found."
          if [[ $MATCH_COUNT -gt 0 ]]; then
            echo "##vso[task.setvariable variable=SOURCE_CODE_CHANGED;isOutput=true]true"
            echo "##vso[task.setvariable variable=db;isOutput=true]$s"
            echo "$p" > version/changefolder.txt
          else
            echo "##vso[task.setvariable variable=SOURCE_CODE_CHANGED;isOutput=true]false"
          fi
        else
          echo "##vso[task.setvariable variable=SOURCE_CODE_CHANGED;isOutput=true]false"
          echo "Empty commithash"
        fi
        echo "######################################"
        echo "##########Changed Database############"
        echo "######################################"
        echo "$p"
        echo "######################################"
        echo "###########Update gitHub##############"
        echo "######################################"
        push_git_changers
        echo "######################################"
      name: check_changes
      displayName: 'Check changed files'
  - job: VerifyLiquibase 
    dependsOn: CheckChanges
    condition: eq(dependencies.CheckChanges.outputs['check_changes.SOURCE_CODE_CHANGED'], 'true')
    variables: 
      AllFileNames: $[dependencies.CheckChanges.outputs['check_changes.db']]
    steps:
    - checkout: self
    - template: templates/displaydb.yaml
      parameters: 
        files: $(AllFileNames)
  - job: UpdateCommithash
    dependsOn: VerifyLiquibase 
    steps:
    - checkout: self
    - script: |
        echo "#############previous##################"
        echo  $(cat version/commithash.txt)
        echo "######################################"
        echo "##############   new   ###############"
        echo $(Build.SourceVersion)
        echo "######################################"
        echo "$(Build.SourceVersion)" > version/commithash.txt