resources:
  repositories:
    - repository: BASE_REPOSITORY
      type: github
      name: nikeshi99/git-log
      ref: refs/heads/main
      endpoint: nikeshi99
trigger: 
  branches:
    include:
    - main
  paths:
    include:
    - .azure/git-diff.yaml
pr: none
stages:
- stage: UpdatingDatabase
  pool:
    vmImage: 'ubuntu-latest'
  jobs:
  - job: CheckChanges
    displayName: 'Check changes'
    steps:
    - checkout: BASE_REPOSITORY
    - bash: |
        push_git_changers () {
          git config --global user.email "nikeshikumarasinghe@gmail.com"
          git config --global user.name "Nikeshi Kumarasinghe"
          git diff
          git commit -am "Update image tags in $(Build.BuildNumber)"
          git pull
          git push
        }
        if [ -s version/commithash.txt ]; then
          previous=$(cat version/commithash.txt)
          PATH_FILTER="logs/"
          CHANGED_FILES$(git diff previous...$(Build.SourceVersion) --name-only)
          MATCH_COUNT=0
          for FILE in $CHANGED_FILES
          do
            if [[ $FILE == *$PATH_FILTER* ]]; then
              echo "MATCH:  ${FILE} changed"
              MATCH_COUNT=$(($MATCH_COUNT+1))
            else
              echo "IGNORE: ${FILE} changed"
            fi
          done
          echo "$MATCH_COUNT match(es) for filter '$PATH_FILTER' found."
          if [[ $MATCH_COUNT -gt 0 ]]; then
            echo "##vso[task.setvariable variable=SOURCE_CODE_CHANGED;isOutput=true]true"
            echo "$(Build.SourceVersion)" > version/commithash.txt
          else
            echo "##vso[task.setvariable variable=SOURCE_CODE_CHANGED;isOutput=true]false"
          fi
        else
          echo "$(Build.SourceVersion)" > version/commithash.txt
        fi
        push_git_changers
      name: check_changes
      displayName: 'Check changed files'
  - job: VerifyLiquibase 
    dependsOn: CheckChanges
    condition: eq(dependencies.CheckChanges.outputs['check_changes.SOURCE_CODE_CHANGED'], 'true')
    steps:
    - checkout: self
    - script: |
        echo "File change detected"
