trigger: none
pr: none
stages:
- stage: Build
  pool:
    vmImage: 'ubuntu-latest'
  jobs:
  # - job: DockerBuild    
  #   steps:
  #   - checkout: self
  #   - task: Docker@2
  #     inputs:
  #       containerRegistry: 'Docker Hub'
  #       repository: 'nikeshi/databaseAutomationTesting'
  #       command: 'buildAndPush'
  #       Dockerfile: 'app/data-backed-service/Dockerfile'   
  #       buildContext: 'app/data-backed-service/'
  #       tags: |
  #        v2 
  - job: DockerBuildLiquibase
    steps:
    - checkout: self
    - task: Docker@2
      inputs:
        containerRegistry: 'Docker Hub'
        repository: 'nikeshi/liquibase'
        command: 'buildAndPush'
        Dockerfile: 'Liquibase/Dockerfile'
        buildContext: 'Liquibase/'
        tags: |
          v2 