trigger: none
pr: none
parameters:
  - name: commithash
    displayName: Enter commit hash
    type: string
resources:
  containers: 
  - container: Liquibase
    image: nikeshi/liquibase:v1
stages:
- stage: rollbackDBVersion
  pool:
    vmImage: 'ubuntu-latest'
  jobs:
  - job: revertDB 
    container: Liquibase
    steps:
    - checkout: self
    - script: |
        liquibase --defaultsFile=Liquibase/liquibase.properties --logLevel=info rollbackSQL version_${{parameters.commithash}}
        liquibase --defaultsFile=Liquibase/liquibase.properties --logLevel=info rollback version_${{parameters.commithash}}
- stage: revertRepo
  dependsOn: rollbackDBVersion
  pool:
    vmImage: 'ubuntu-latest'
  jobs:
  - job: revertChangelogFiles
    steps:
    - checkout: self
    - script: |
        git reset --hard ${{parameters.commithash}} -- Liquibase/db/changelog
        commits=($(git log origin/main -n 2 --pretty=format:"%H" -- Liquibase/db/changelog))
        git checkout ${commit[1]} -- Liquibase/db/changelog
        git commit -m "rollback db changes version_${{parameters.commithash}}"