trigger: none
pr: none
parameters:
  - name: commithash
    displayName: Enter commit hash
    type: number
resources:
  containers: 
  - container: Liquibase
    image: nikeshi/liquibase:v1
stages:
- stage: rollback
  pool:
    vmImage: 'ubuntu-latest'
  jobs:
  - job: revertDB 
    container: Liquibase
    steps:
    - checkout: self
    - script: |
        liquibase --defaultsFile=Liquibase/liquibase.properties --logLevel=info rollbackSQL nikeshi_${{commithash}}
        liquibase --defaultsFile=Liquibase/liquibase.properties --logLevel=info rollback nikeshi_${{commithash}}
- stage: revertRepo
  pool:
    vmImage: 'ubuntu-latest'
  job:
  - job: revertChangelogFiles
    steps:
    - checkout: self
    - script: |
        git reset --hard ${{commithash}} --path Liquibase/db/changelog/