resources:
  repositories:BASE_REPOSITORY
    - repository: 
      type: github
      name: nikeshi99/git-log
      ref: refs/heads/main
      endpoint: nikeshi99
trigger: 
  branches:
    include:
    - main
  paths:
    include:
    - .azure/loopDB.yaml
    - .azure/templates/gitdiff.yaml
    - logs/
pr: none

parameters:
- name: databases
  type: object
  default:
  - db1
  - db2
  - db3
  - db4
  - db5
  - db6
  - db7
  - db8
  - db9
  - db10
  
stages:
  - stage: UpdatingDatabase
    pool:
      vmImage: 'ubuntu-latest'
    jobs:
    - job: ApplyChanges
      displayName: 'Check changes'
      steps:
        - ${{each db in parameters.databases}}:
          - template: templates/gitdiff.yaml
            parameters:
              DB: ${{db}}
               