resources:
  repositories:
    - repository: BASE_REPOSITORY
      type: github
      name: nikeshi99/git-log
      ref: refs/heads/main
      endpoint: nikeshi99
trigger: 
  branches:
    include:
    - main
  paths:
    include:
    - .azure/loopDB.yaml
    - .azure/templates/gitdiff.yaml
    - logs/
pr: none

parameters:
- name: databases
  type: object
  default:
  - db1
  - db2
  - db3
  
stages:
  - stage: UpdatingDatabase
    pool:
      vmImage: 'ubuntu-latest'
    jobs:
    - job: ApplyChanges
      displayName: 'Check changes'
      steps:
        - checkout: self
        - ${{each db in parameters.databases}}:
          - template: templates/gitdiff.yaml
            parameters:
              DB: ${{db}}
               