resources:
  repositories:
    - repository: BASE_REPOSITORY
      type: github
      name: nikeshi99/git-log
      ref: refs/heads/main
      endpoint: nikeshi99
trigger: 
  branches:
    include:
    - main
  paths:
    include:
    - .azure/loopDB.yaml
    - .azure/templates/gitdiff.yaml
    - logs/
pr: none

parameters:
- name: databases
  type: object
  default:
  - db1
  - db2
  - db3
  - db4
  - db5
  - db6
  - db7
  - db8
  - db9
  - db10
  
stages:
  - stage: UpdatingDatabase
    pool:
      vmImage: 'ubuntu-latest'
    jobs:
    - job: ApplyChanges
      displayName: 'Check changes'
      steps:
      - checkout: BASE_REPOSITORY
      - checkout: self
        persistCredentials: true
      - ${{each db in parameters.databases}}:
        - template: templates/gitdiff.yaml
          parameters:
            DB: ${{db}}
      - bash: |
          push_git_changers () {
            git config --global user.email "nikeshikumarasinghe@gmail.com"
            git config --global user.name "Nikeshi Kumarasinghe"
            git diff
            git commit -am "Update succeeded commithash in $(Build.SourceVersion)"
            git remote -v
            git branch -al
            if git push origin HEAD:main ; then
              echo "Changes pushed successfully"
            else
              git fetch origin
              git merge --no-edit --strategy recursive --strategy-option theirs origin/main
              git push origin HEAD:main
            fi
          }
          push_git_changers


               