FROM liquibase/liquibase
USER root
# ENV URL=jdbc:mysql://35.244.39.57:3306/DBdev
# ENV USERNAME=nikeshi
# ENV PASSWORD=Wso2@123
# COPY lib/mysql-connector-java-8.0.29.jar .
# ENV LIQUIBASE_DRIVER=com.mysql.cj.jdbc.Driver
# ENV LIQUIBASE_CLASSPATH=lib/mysql-connector-java-8.0.29.jar
#ENV CHANGELOGFILE=database-automation-testing/Liquibase/db/master.mysql.xml
